workflows:
  ios-build:
    name: iOS Godot Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Clone SwiftGodot and build xcframework
        script: |
          git clone https://github.com/migueldeicaza/SwiftGodot.git
          cd SwiftGodot
          # Assuming you have a preconfigured Xcode project to build it as xcframework
          xcodebuild -workspace SwiftGodot.xcworkspace -scheme SwiftGodot -configuration Release
          # Copy the xcframework to the iOS directory of your Flutter project
          cp -r build/Release-iphoneos/SwiftGodot.xcframework ../ios/Flutter/SwiftGodot.xcframework
      - name: Build iOS project
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
