workflows:
  ios-build:
    name: iOS Godot Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS project
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
